### ISSUE TITLE
Seriously, do all the job in PHP, and let Python away

### ISSUE THREAD

**Issue by davidak** [KeitIG/elementary-stats#4]
why not "do all the job in Python and let PHP away"

**Comment by KeitIG** [comment]
I'm a PHP dev, I don't know Python so much, but after my full PHP refactoring, you could port it in python if you want :)

**Comment by davidak** [comment]
if you know what you are doing php maybe is ok.

i think python has the best compromise between performance and easy syntax.

**Comment by KeitIG** [comment]
Well, Python in my opinion has a great advantage: file reading and writing, meanwhile it is a bit complicated with PHP without abusive file permissions or change PHP ownership on the server.

I'm letting this issue opened for the moment while I'm thinking about this.

**Comment by KeitIG** [comment]
Well, I used PHP for the moment, it doesn't really matter because of we official devs are working on a similar project with other techs.
