### ISSUE TITLE
Rewrite from Scratch

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/elementary-stats#5]
- [x] Rewrite the whole stuff in PHP #4 
- [x] index.php refactoring
- [x] Get Cron tasks working #3 
- [x] Fix freya-rc1 not updating

**Comment by KeitIG** [comment]
We're done.

**Comment by davidak** [comment]
n1ce

**Comment by davidak** [comment]
are the changes live?

**Comment by KeitIG** [comment]
yes they are, I just fixed a bug this morning, the server was writing in parent folder instead of /www/

**Comment by davidak** [comment]
at this page: http://elementarybugs.org/ ?

i see 2x beta2, should i see rc1?

**Comment by KeitIG** [comment]
god thanks
