### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by kaldoran** [KeitIG/elementary-stats#7]
You should probably update on the new branch after released : 
https://launchpad.net/elementary/+milestone/freya-rc1

On http://stats.elementaryos.org/
But dunno if you hold this.
Thanks ;)

**Comment by kaldoran** [comment]
PS : it's on http://stats.elementaryos.org/

**Comment by martpie** [comment]
Hehe, the project was "merged" to the main repo https://github.com/elementary/mvp ;)
